# Generated by Django 5.1.5 on 2025-05-08 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0002_articlescommande_prix_unitaire_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='image_url',
        ),
        migrations.AddField(
            model_name='produit',
            name='animal',
            field=models.CharField(choices=[('Chien', 'Chien'), ('Chat', 'Chat'), ('Les deux', 'Les deux')], default='Chien', max_length=10),
        ),
        migrations.AddField(
            model_name='produit',
            name='image',
            field=models.ImageField(default='products/default.jpg', upload_to='products/'),
            preserve_default=False,
        ),
    ]
