# Generated by Django 5.1.5 on 2025-05-08 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0003_remove_produit_image_url_produit_animal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='animal',
        ),
    ]
