# Generated by Django 5.1.5 on 2025-02-10 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='sexe',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Femelle')], max_length=1),
        ),
    ]
