# Generated by Django 5.1.5 on 2025-04-04 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0003_historiquedemandeadoption'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvenementMarcheChien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('heure', models.TimeField()),
                ('lieu', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('chiens', models.ManyToManyField(related_name='evenements_marche', to='animals.animal')),
            ],
            options={
                'verbose_name': 'Événement de marche',
                'verbose_name_plural': 'Événements de marche',
            },
        ),
        migrations.CreateModel(
            name='DemandeEvenementMarche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('En attente', 'En attente'), ('Acceptee', 'Acceptee'), ('Refusee', 'Refusee')], default='En attente', max_length=10)),
                ('chiens', models.ManyToManyField(related_name='demandes_marche', to='animals.animal')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('evenement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes', to='animals.evenementmarchechien')),
            ],
            options={
                'verbose_name': "Demande d'événement de marche",
                'verbose_name_plural': "Demandes d'événements de marche",
            },
        ),
    ]
