# Generated by Django 5.1.5 on 2025-05-13 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0004_merge_20250415_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandegarde',
            name='date_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demandegarde',
            name='date_reservation',
            field=models.DateField(blank=True, null=True),
        ),
    ]
