# Generated by Django 5.1.5 on 2025-05-14 10:54

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0005_demandegarde_date_fin_demandegarde_date_reservation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandegarde',
            name='date_fin',
            field=models.DateField(default=datetime.date(2025, 12, 31)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='demandegarde',
            name='date_reservation',
            field=models.DateField(default=datetime.date(2025, 12, 31)),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Adoption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_adoption', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adoptions', to='animals.animal')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adoptions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Garderie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField(auto_now_add=True)),
                ('date_fin', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='animaux/')),
                ('type_garde', models.CharField(choices=[('Temporaire', 'Temporaire'), ('Définitive', 'Définitive')], default='Temporaire', max_length=20)),
                ('animal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='garderie', to='animals.animal')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='garderie', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Garderie',
                'verbose_name_plural': 'Garderies',
            },
        ),
    ]
